baseURL: https://rohandebsarkar.codeberg.page
languageCode: en
title: Rohan Deb Sarkar
copyright: © Copyright 2023 Rohan Deb Sarkar

# theme: academic-folio

enableEmoji: false

enableRobotsTXT: true

markup:
  highlight:
    guessSyntax: true
    style: dracula  # syntax highlighting style for markdown code blocks
                    # choose a style from https://xyproto.github.io/splash/docs/all.html

module:
  imports:
  - path: github.com/rohandebsarkar/academic-folio
  - path: github.com/FortAwesome/Font-Awesome
    mounts:
    - source: svgs
      target: assets/svgs/fontawesome
