main:
- name: Blog
  url: /posts/
  weight: 1

- name: Curriculum Vitae
  url: https://rohandebsarkar.github.io/.resume/resume.pdf
  weight: 2

- name: Projects
  url: /projects/
  weight: 3

social:
- name: email
  url: rohandebsarkar@protonmail.com
  weight: 1
  params:
    icon: fas fa-envelope

- name: LinkedIn
  url: https://www.linkedin.com/in/rohandebsarkar
  weight: 2
  params:
    icon: fab fa-linkedin

- name: GitHub
  url: https://github.com/rohandebsarkar
  weight: 3
  params:
    icon: fab fa-github

- name: RSS Feed
  url: /index.xml
  weight: 4
  params:
    icon: fas fa-square-rss
