firstName: Rohan Deb
lastName: Sarkar

email: rohandebsarkar@protonmail.com

description: Undergarduate physics student at <a href="https://rkmvccrahara.org" target="_blank" rel="external nofollow noopener">Ramakrishna Mission Vivekananda Centenary College</a>

tags: # these tags would be added as keywords in metadata for website
- academic-folio
- academic-website
- al-folio
- hugo
- hugo-theme

maxWidth: 1024px

navbarTitle: true # displays the title in the navbar on non home pages

footerLastUpdated: true

recentPosts: 5 # number of recent posts to show in home page
showRecentPosts: false

recentNews: 5 # number of recent news to show in home page
showRecentNews: false

socialNavbar: true # show social icons on navbar
socialHomePage: true # show social icons on the home page

colorTheme: blue # choose a theme from `data/themes` folder

analyticsScript: <script async src="https://perpetuus.vercel.app/motus.js" data-website-id="fea030e7-3e19-4a29-86b7-6bef67af88be"></script>
