clone:
  git:
    image: woodpeckerci/plugin-git

pipeline:
  # Build hugo static files
  build:
    image: klakegg/hugo:ext-alpine-ci
    commands:
      - hugo --minify
    when:
      event: [ pull_request, push ]

  publish:
    image: bitnami/git
    # Must be set in Woodpecker configuration
    secrets: [ mail, codeberg_token ]
    environment:
      - HUGO_OUTPUT=public
      - DEPLOY_REPO=pages
    commands:
      # Git configuration
      - git config --global user.email ""
      - git config --global user.name "Codeberg CI"
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO_OWNER/$DEPLOY_REPO.git $DEPLOY_REPO
      - cd $DEPLOY_REPO
      - git rm -r *
      # Copy build step output to repository folder
      - cp -ar ../$HUGO_OUTPUT/. .
      # Needed for custom domains
      - cp ../.domains . || true # Ignore if it doesn't exist
      - git add .
      - git commit --allow-empty -m "Woodpecker CI build created from ${CI_REPO}@${CI_COMMIT_SHA} [CI SKIP]"
      - git push
    when:
      event: push

branches:
  exclude: [ pages ]